### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Loodoor** [Reiex/Endless-rooms#1]
Yop.

Tu devrais essayer d'adopter un code style plus uniforme, car : 

```python
if mode == "tuto":
    image = "images/tuto/"+str(blabla)+".png"
else:
    image = "images/normal/"+str(blabla)+".png"
```

C'est remplacable par : 

```python
image = "images/{}/{}.png".format("tuto" if mode else "normal", blabla)
```

Ensuite tu fais enfin de la POO c'est cool ;)

Après, tu as pas mal de magic constants comme dans etage.py ligne 53 : tu fais un * 64. Ok moi je comprends que 64 est la taille de tes tiles, mais ce serait pas mieux de tout foutre dans un fichier si un jour tu veux changer la taille de tes tiles ? Ou si quelqu'un d'autre veut lire ton code, il comprendra pas forcément ...

Ligne 72 à 116 dans etage.py, tu devrais utiliser un dico ;)

Genre : 

```python
truc = {
    sf.Color(255, 0, 0): 12
}
for i in niveau:
    if i in truc:
        blocs.append(truc[i])
```

Ici si i == sf.Color(255, 0, 0), alors on ajoutera 12 à blocs.

C'est tout ce que j'ai remarqué d'important pour le moment :)

**Comment by Reiex** [comment]
Alors, pour lire l'étage, je savais pas que .format pouvait s'utiliser comme ça x) Je mettrais ça dans le code.
Pour la taille des tiles... c'est un peu par habitude, et puis s'il veut les voir il ouvre "tileset.png" avec paint, il sélectionne un bloc, il voit que ça fait 64*64
Pour le dico... je sais pas si ça serait pas moins lisible du coup...
