### ISSUE TITLE
Crash quand le nombre de session est trop gand

### ISSUE THREAD

**Issue by Skolopedrion** [Reiex/Endless-rooms#2]
Fix: implémenter une scrollbar pour le menu des saves.

**Comment by Reiex** [comment]
Oui, ça va venir, mais c'est pas une priorité, t'en fais pas de nombreux types de menus vont venir, d'ailleurs le menu de choix de session donnera plus de libertés (possibilité de renommer ou effacer des sessions)

**Comment by Reiex** [comment]
De plus pour ta branche, a l'instant ou j’écris c'est surtout des changements pour appeler [] au lieu de list(), c'est juste plus lisible pour moi quand on met list(), d'ailleurs, c'est ce que recommande mon IDE (Pycharm) qui est souvent a cheval sur ce genre de détails, c'est d'ailleurs aussi valable pour les dict(), str() etc...
Pour ce qui est de faire des attributs "self.texture_impacte" et "self.texture_projectile", je préfère garder un dict parce que j'aurais pas mal d'autres attaques a ajouter plus tard, et que chaque attaque n'utilisera pas toutes ces textures, or la classe sert pour toutes les attaques, donc pour éviter les attributs inutiles, le dict est un peu mieux (et puis parce que c'est plus pratique a appeler =P)
Par conte je garde le "while not variable" au lieu de "while variable == list()"

**Comment by Reiex** [comment]
Fixed
